- hosts: all
  vars:
    microk8s_channel: 1.15/stable
  roles:
    - environment_setup
    - install_microk8s
    - enable_services
    - rbac_access_dashboard
    - rbac_access_tiller
    - install_tiller
    - export_kubeconfig
    - export_dashboard_token
